import Head from 'next/head'
import Image from 'next/image'

// importing Components
import Navbar from '../components/nav';
import Main from '../components/main';
import Services from '../components/Services';
import Partner from '../components/partners';

export default function Home() {
  return (

<div>
    <style jsx> 
    {
      `
        main {
          background-color : #FBF9F5;
        }

      `
    }
    </style>


      <Head>
        <title>User Interface</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <header>
        <Navbar />
      </header>

      <main >
          <Main />    
      </main>

      <section>
          <Services />

      </section>

      <section>
        <Partner />
      </section>

      
    </div>
  )
}
